from transformers import AutoTokenizer, AutoModelForCausalLM, AutoModel
import torch
import pickle

# local_model_path = '/home/gridsan/cliu/hf/Mistral-7B-Instruct-v0.2'
# local_model_path = '/home/gridsan/cliu/hf/dbrx-instruct/'
model_name = "/home/gridsan/cliu/hf/Meta-Llama-3-8B-Instruct"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name, output_attentions=True, load_in_4bit=True, device_map="auto")

contexts =  ["""A Deep Dive into Common Open Formats for Analytical DBMSs
            Chunwei Liu MIT CSAIL chunwei@csail.mit.edu
            Anna Pavlenko Microsoft annapa@microsoft.com
            Matteo Interlandi Microsoft mainterl@microsoft.com
            Brandon Haynes Microsoft brhaynes@microsoft.com
            ABSTRACT
            This paper evaluates the suitability of Apache Arrow, Parquet, and ORC as formats for subsumption in an analytical DBMS. 
            """,
            """A DECLARATIVE SYSTEM FOR OPTIMIZING AI WORKLOADS
            A PREPRINT
            Chunwei Liu*
            , Matthew Russo*
            , Michael Cafarella,
            Lei Cao†
            , Peter Baille Chen, Zui Chen, Michael Franklin‡
            ,
            Tim Kraska, Samuel Madden, Gerardo Vitagliano
            MIT, †University of Arizona, ‡University of Chicago
            chunwei@mit.edu, mdrusso@mit.edu, michjc@csail.mit.edu
            caolei@arizona.edu, peterbc@mit.edu, chenz429@mit.edu, mjfranklin@uchicago.edu,
            kraska@mit.edu, madden@csail.mit.edu, gerarvit@csail.mit.edu
            ABSTRACT
            A long-standing goal of data management systems has been to build systems which can compute
            quantitative insights over large corpora of unstructured data in a cost-effective manner. Until recently,
            it was difficult and expensive to extract facts from company documents, data from scientific papers, or
            metrics from image and video corpora. Today’s models can accomplish these tasks with high accuracy.
            """,
             """Detecting AI-Generated Text: Factors Influencing\nDetectability with Current Methods\nKathleen C. 
             Fraser\nkathleen.fraser@nrc-cnrc.gc.ca\nHillary Dawkins\nhillary.dawkins@nrc-cnrc.gc.ca\nSvetlana 
             Kiritchenko\nsvetlana.kiritchenko@nrc-cnrc.gc.ca\nNational Research Council Canada\n1200 Montreal Road, 
             Ottawa, Canada\nAbstract\nLarge language models (LLMs) have advanced to a point that even humans have 
             dif-\nficulty discerning whether a text was generated by another human, or by a computer.\nHowever, 
             knowing whether a text was produced by human or artificial intelligence (AI)\nis important to 
             determining its trustworthiness, and has applications in many domains\nincluding detecting fraud and 
             academic dishonesty, as well as combating the spread of mis-\ninformation and political propaganda. The 
             task of AI-generated text (AIGT) detection is\ntherefore both very challenging, and highly critical. In 
             this survey, we summarize state-\nof-the art approaches to AIGT detection, including watermarking, 
             statistical and stylistic\nanalysis, and machine learning classification.""",
             """A Lived Informatics Model of Personal Informatics\nDaniel A. Epstein 1 , An Ping 2 , James Fogarty 1 , Sean A. Munson 2\n1 Computer Science & Engineering, 2 Human Centered Design & Engineering\nDUB Group, University of Washington\n{depstein, jfogarty}@cs.washington.edu, {anping, smunson}@uw.edu\nABSTRACT\nCurrent models of how people use personal informatics\nsystems are largely based in behavior change goals. They do\nnot adequately characterize the integration of self-tracking\ninto everyday life by people with varying goals. We build\nupon prior work by embracing the perspective of lived\ninformatics to propose a new model of personal informatics.""",
             """A Stage-Based Model of Personal Informatics Systems\nIan Li 1 , Anind Dey 1 , and Jodi Forlizzi 1,2\n1 Human Computer Interaction Institute, 2 School of Design\nCarnegie Mellon University, Pittsburgh, PA 15213\nianli@cmu.edu, {anind, forlizzi}@cs.cmu.edu\nABSTRACT\nPeople strive to obtain self-knowledge. A class of systems\ncalled personal informatics is appearing that help people\ncollect and reflect on personal information. However, there\nis no comprehensive list of problems that users experience\nusing these systems, and no guidance for making these\nsystems more effective. To address this, we conducted\nsurveys and interviews with people who collect and reflect\non personal information.""",
             """A Stage-Based Model of Personal Informatics Systems\n ABSTRACT\nPeople strive to obtain self-knowledge. A class of systems\ncalled personal informatics is appearing that help people\ncollect and reflect on personal information. However, there\nis no comprehensive list of problems that users experience\nusing these systems, and no guidance for making these\nsystems more effective. To address this, we conducted\nsurveys and interviews with people who collect and reflect\non personal information. Ian Li 1 , Anind Dey 1 , and Jodi Forlizzi 1,2\n1 Human Computer Interaction Institute, 2 School of Design\nCarnegie Mellon University, Pittsburgh, PA 15213\nianli@cmu.edu, {anind, forlizzi}@cs.cmu.edu\n"""]

questions = ["What is the paper title?",
            "What is the authors of the paper?"]

for i in range(len(contexts)):
    for j in range(len(questions)):
        print (f"Context {i}, Question {j}")
        context = contexts[i]
        question = questions[j]
        if context.strip():
            prompt = f"Context: {context}\nQuestion: {question}\nAnswer:"
        else:
            prompt = f"Question: {question}\nAnswer:"

        inputs = tokenizer.encode(prompt, return_tensors='pt')
        outputs = model(inputs)
        print(outputs)
        attention = outputs[-1]
        tokens = tokenizer.convert_ids_to_tokens(inputs[0])
        # save the attention weights into a file


        with open(f'../data/tensor/context{i}-question{j}_attention.pkl', 'wb') as f:
            pickle.dump(attention, f)

        # save the tokens into a file
        with open(f'../data/tensor/context{i}-question{j}_tokens.pkl', 'wb') as f:
            pickle.dump(tokens, f)
print(f"Done with {len(contexts)} contexts and {len(questions)} questions")